# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T04:14:56+00:00



import argparse
import json
import os
from typing import *

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity, HTTPBasic
from fastapi import Path
from starlette.requests import Request

from models import MaintenanceIssueModel, Object

app = MCPProxy(
    contact={'x-twitter': 'agentOSSoftware'},
    title='agentOS API V3, Maintenance Call Group',
    version='v3-maintenance',
    servers=[{'url': 'https://live-api.letmc.com'}],
)


@app.post(
    '/v3/maintenance/{shortName}/maintenance/{branchID}/createmaintenancejob',
    tags=['maintenance_job_management'],
)
def maintenance_controller__create_maintenance_job(
    short_name: str = Path(..., alias='shortName'),
    branch_i_d: str = Path(..., alias='branchID'),
    body: MaintenanceIssueModel = ...,
):
    """
    Create a maintenance job for a specific branch
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
