# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T04:14:56+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class MaintenanceDocumentModel(BaseModel):
    MimeType: Optional[str] = Field(None, description='The document Mime Type')
    URL: Optional[str] = Field(
        None, description='The document URL (This has to be public)'
    )


class IssuePriority(Enum):
    Low = 'Low'
    Medium = 'Medium'
    High = 'High'


class MaintenanceIssueModel(BaseModel):
    Documents: Optional[List[MaintenanceDocumentModel]] = Field(
        None, description='Documents linked to a submitted maintenance job'
    )
    ExternalID: Optional[str] = Field(
        None,
        description='ID used externally to manage jobs before sending to the system. This has a 10 character limit.',
    )
    IssueFault: Optional[str] = Field(None, description='The fault title if applicable')
    IssueNotes: Optional[str] = Field(None, description='Fault notes')
    IssuePriority_1: Optional[IssuePriority] = Field(
        None,
        alias='IssuePriority',
        description="The priority of the job (Defaults to 'Low' if incorrect value or empty)",
    )
    IssueTitle: Optional[str] = Field(None, description='The title of the issue')
    PropertyAddress1: Optional[str] = Field(
        None, description='The first line of the property address'
    )
    PropertyAddress2: Optional[str] = Field(
        None, description='The second line of the property address'
    )
    PropertyAddress3: Optional[str] = Field(
        None, description='The third line of the property address'
    )
    PropertyAddress4: Optional[str] = Field(
        None, description='The forth line of the property address'
    )
    PropertyCountry: Optional[str] = Field(
        None, description='The country the property is located'
    )
    PropertyPostcode: Optional[str] = Field(None, description='The property postcode')
    ReportedAt: Optional[datetime] = Field(
        None, description='The date the job was reported'
    )
    TenantEMailAddress: Optional[str] = Field(
        None, description='The email address of the Tenant'
    )
    TenantForename: Optional[str] = Field(
        None, description='The forename of the Tenant'
    )
    TenantPhonePrimary: Optional[str] = Field(
        None, description='The primary phone number of the Tenant'
    )
    TenantPhoneSecondary: Optional[str] = Field(
        None, description='The secondary phone number of the Tenant'
    )
    TenantPresenceRequested: Optional[bool] = Field(
        None,
        description='Is the Tenant’s presence requested during the maintenance visit? (Defaults to “false” if incorrect value or empty)',
    )
    TenantSurname: Optional[str] = Field(None, description='The surname of the Tenant')
    TenantTitle: Optional[str] = Field(None, description='The title of the Tenant')


class Object(BaseModel):
    pass
